name: Checkmarx AST Scan
on:
  pull_request:
    types: [opened, reopened, synchronize] #Types specify which pull request events will trigger the workflow. For more events refer Github Actions documentation.
    branches:
      - master
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action versionn
        with:
          # Provide the AST portal URL
          base_uri: https://eu.ast.checkmarx.net/
          # Provide the Tenant for AST portal URL
          cx_tenant: soniadias-production
          # Client ID for AST portal authentication
          cx_client_id: ${{ secrets.CXONE_CLIENT_ID }}
          # Secret key for AST portal authentication
          cx_client_secret: ${{ secrets.CXONE_SECRET }}
          # Select a Checkmarx Project Name
          #project_name: # optional, default is ${{ github.repository }}
          # Branch name
          #branch: # optional, default is ${{ github.head_ref || github.ref }}
          # GitHub API Token
          #github_token: # optional, default is ${{ github.token }}
          # Additional parameters for AST scan
          additional_params: --report-format sarif --output-path . --sast-preset-name "Checkmarx Default"
          # Repository name for PR decoration
          #repo_name: # optional, default is ${{ github.event.repository.name }}
          # Organization name to create the Pr comment
         # namespace: # optional, default is ${{ github.repository_owner }}
          # Pr Number of the pull request that needs the decoration
          #pr_number: # optional, default is ${{ github.event.number }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: cx_result.sarif
          
